Adds a default content-type to StaticFiles and NamedFile
SergioBenitez/Rocket pull request #1413
Opened 2020-08-16 18:31 UTC by pwoolcoc

Closes #1397

2020-08-17 14:09 UTC, pwoolcoc commented
SInce the content-type header is set in `NamedFile`s implementation of `Responder`, it was easiest to add the default content-type to that type as well

2020-08-25 17:54 UTC, pwoolcoc commented
@SergioBenitez any chance I could get a look at this?

2020-11-01 18:30 UTC, SergioBenitez requested changes

2020-11-01 18:30 UTC, SergioBenitez commented on core/lib/src/response/named_file.rs
> +    pub fn default_type(&mut self, content_type: ContentType) -> &mut Self {
I would rather this be a builder method, taking `self` by value.
```suggestion
    pub fn with_default(mut self, content_type: ContentType) -> Self {
```

Then the example can be:

```rust
#[get("/<path..>")]
fn file(path: PathBuf) -> Result<NamedFile, Debug<io::Error>> {
    Ok(NamedFile::open(path).await?.with_default(ContentType::Plain))
}
```

Which I think is much more illustrative.

2020-11-01 18:30 UTC, SergioBenitez commented on core/lib/src/response/named_file.rs
> +pub struct NamedFile(PathBuf, File, Option<ContentType>);
This should probably have named fields at this point:

```rust
pub struct NamedFile {
    path: PathBuf,
    file: File,
    default_ct: Option<ContentType>,
}
```

2020-11-01 18:30 UTC, SergioBenitez commented on core/lib/src/response/named_file.rs
> +    /// Sets the default content type for the file
```suggestion
    /// Sets the default Content-Type.
```

2020-11-01 18:30 UTC, SergioBenitez commented on core/lib/src/response/named_file.rs
> +    /// have an extension, no content-type header will be sent.
Perhaps:

Ordinarily, when responding, if the file path to `self` does not have an extension, or if the extension does not have a known Content-Type (see [`ContentType::from_extension()`]), no Content-Type is set in the response. By setting a default, the Content-Type of the response will be set to `content_type`.

2020-11-01 18:30 UTC, SergioBenitez commented on core/lib/src/response/named_file.rs
>          }
```suggestion
        let content_type = self.path.extension()
            .and_then(|e| e.to_str())
            .and_then(ContentType::from_extension)
            .or(self.default_ct);
        
        if let Some(content_type) = content_type {
            response.set_header(content_type);
        }
```

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +    pub fn default_type(mut self, content_type: ContentType) -> Self {
```suggestion
    pub fn with_default(mut self, content_type: ContentType) -> Self {
```

To match `with_default` in `NamedFile`.

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +    /// for the content-type header
Let's also change this to be more inline with my suggestions for the `NamedFile::with_default()` docstring.

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +    };
```suggestion
    let file = NamedFile::open(p.as_ref().join("index.html")).await
        .map(|file| match default_ct {
            Some(default) => file.with_default(default_ct.clone()),
            None => file
        }).ok();
```

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +async fn handle_dir<'r, P>(opt: Options, r: &'r Request<'_>, d: Data, p: P, content_type: Option<&ContentType>) -> Outcome<'r>
```suggestion
async fn handle_dir<'r, P>(opt: Options, r: &'r Request<'_>, d: Data, p: P, default_ct: Option<&ContentType>) -> Outcome<'r>
```

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +    content_type: Option<ContentType>,
```suggestion
    default_ct: Option<ContentType>,
```

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +                        println!("setting default content-type");
Don't print this.

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/src/serve.rs
> +                let file = {
These are almost exactly the same lines as in `handle_dir`: dedup these.

2020-11-01 18:30 UTC, SergioBenitez commented on contrib/lib/tests/static_files.rs
> +            .mount("/no_extension_with_default", StaticFiles::new(&root, Options::None).default_type(ContentType::Plain))
Do we need `Options` at all here? Why not just `StaticFiles::from(&root).with_default(ContentType::Plain)`?

2021-03-10 11:10 UTC, SergioBenitez commented
@pwoolcoc Do you have interest in continuing this?

2021-04-05 19:54 UTC, closed without merging