Added DerefMut impl to Form and LenientForm
SergioBenitez/Rocket pull request #1445
Opened 2020-10-10 08:39 UTC by ThouCheese

I ran into a limitation with `Form` where I needed to modify the inner data, but the `DerefMut` implementation was missing. I have also added `DerefMut` to `LenientForm` for consistency.

2020-10-11 21:03 UTC, jebrosen commented
From the matrix chat:
> ThouCheese: Is there a reason why Form<T> and LenientForm<T> implement Deref<Target=T>, but not DerefMut?
> Sergio: Don't think so. There used to be, but I can't think of a reason for why now.

Prior to ec4cc3a `Form` was self-referential, so mutable access would have been quite dangerous. Now that `Form<T>` is just a wrapper around `T`, and #810 even made the field public, I can't think of a good reason not to add this.

2020-10-11 21:06 UTC, jebrosen requested changes
The docs for `Form<T>` say ``automatically dereferences into an `&T` ``. Let's add `&mut T` as well: ``dereferences into an `&T` or `&mut T` ``.

2020-10-12 08:08 UTC, ThouCheese commented
@jebrosen fixed! I cant' figure out why the CI on Linux doesn't work (or how this PR could possibly break anything :sweat:)

2020-10-12 16:48 UTC, jebrosen approved these changes
LGTM. 83a7fc4 in `master` seems to have fixed the CI failure in this PR.

2020-10-21 04:04 UTC, SergioBenitez commented
Merged in 080d586a356b7ffc3617b98ecbc57457f1d9acaa. Thank you!

2020-10-21 04:04 UTC, closed without merging