Run on_launch fairings after effective port is known in config.
SergioBenitez/Rocket pull request #1492
Opened 2020-12-16 16:17 UTC by toxeus

2020-12-17 06:03 UTC, jebrosen requested changes
I believe this is a regression introduced at some point in the configuration revamp (<https://github.com/SergioBenitez/Rocket/commit/1fb061496d0234f84495723e6c95590064778785#diff-f5b44e8d22d6c82ac6288d0d2b08bf8a025e9822ea030c381ce206fae8e4c578R511>). The fix looks okay to me, just a small change requested in the test.

2020-12-17 09:31 UTC, toxeus commented on core/lib/tests/on_launch_fairing_can_inspect_port.rs
> +    let (tx, rx) = sync_channel::<u16>(0);
Fixed

2020-12-17 19:27 UTC, jebrosen approved these changes
This might be the first test that actually tries to listen on a port. The port is set to `0`, so this seems okay to me.

An alternative approach may be to use #1154, which would let us test this functionality another way (but not this particular test).

2021-01-08 14:03 UTC, toxeus commented
Ping @SergioBenitez

2021-01-14 01:21 UTC, SergioBenitez commented
@toxeus Please allow collaborators to push to your branch next time!

2021-01-14 01:34 UTC, SergioBenitez commented
Merged in 48fd83a31de0988e480678be9934f59d0df09f86.

2021-01-14 01:34 UTC, closed without merging