Add 'RouteUri' struct and use instead of base/path/uri on 'Route'
SergioBenitez/Rocket pull request #1578
Opened 2021-03-15 14:22 UTC by sd2k

This PR adds a new `RouteUri` struct (based on the suggestions in #1575) which consolidates the various `base`, `path`, and 'complete' `uri` subsets of a route's URI, and also provides access to the 'complete' URI as a '&str' by storing the full URI as a `String` on the `RouteUri` struct.

Questions:

- do you agree with the changes to 'base', 'path' and 'uri'? This does change the API somewhat, requiring users to go through the `RouteUri` struct to get hold of these things. I can add back the old `base` and `path` methods on `Route` if desired.
- should `RouteUri` be exported as `rocket::RouteUri`? or just `rocket::routes::RouteUri`?
- I'm not sure about the naming of the 'uri' and 'origin' fields/methods - any ideas?

TODO:

- [ ] Add docstring to `RouteUri`
- [ ] Add better docstring to `RouteUri::new`

Closes #1575.

2021-03-17 02:22 UTC, SergioBenitez commented on core/lib/src/lib.rs
> +pub use crate::router::{Route, RouteUri};
This is unfortunate. Perhaps it's time for a `router` module.

2021-03-17 07:49 UTC, SergioBenitez requested changes
I see now that this is much more involved than I anticipated. Instead of leaving a length review, I went ahead and made changes to the code directly. Can you finish off the PR by fixing doctests and filling out any missing docs?

2021-03-18 21:24 UTC, sd2k commented
I've updated the docstrings and docs. Since the `router` module isn't public, `RouteUri` isn't accessible in the docs. Should it be publicly exported somewhere to enable this?

2021-03-19 11:10 UTC, SergioBenitez commented
Merged in 2463637d518f98cf97223e6afde90277af3fcb74, 97acd8d9a9845562e7cc26d259f9790da63a6cc2. I took care of exposing `RouteUri` and adding a docstring for it. Thank you!

2021-03-19 11:10 UTC, closed without merging